title: Jeremy Chia
logo: /assets/images/anime_character_kitti_ai.png
baseurl: jeremychia

collections:
  projects:
    output: true

rrss:
  email: "jeremyjchia@gmail.com"
  github: "https://github.com/jeremychia/"
  linkedin: "https://www.linkedin.com/in/jjchia/"

plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"

defaults:
  - scope:
      path: ""
    values:
      author: "Jeremy Chia"
